### ISSUE TITLE
Loading compiled byte code

### ISSUE THREAD

**Issue by foobert** [kripken/lua.vm.js#24]
I'm trying to load byte code directly using loadbufferx but always get a result of 3 (LUA_ERRSYNTAX). What kind of object to you have to pass to loadbufferx? I've tried Uint8Array et al but none seem to work.

FYI the file is compiled using the bundled luac and doing this in C works as expected.

Any thoughts?

**Comment by daurnimator** [comment]
> I'm trying to load byte code directly using loadbufferx but always get a result of 3 (LUA_ERRSYNTAX).

Where did you get the byte code from? lua bytecode is not portable between platforms: you need to compile it on the target.
e.g. you can use `string.dump` and save the output


> What kind of object to you have to pass to loadbufferx? I've tried Uint8Array et al but none seem to work.

`loadbufferx` takes an char array, the length, name and mode.
Usually you can use `emscripten.intArrayFromString` to convert from a js string to a char array, but it errors when it hits certain binary codepoints (due to `encodeURIComponent` call)
@kripken care to comment on this bit?


> FYI the file is compiled using the bundled luac

We do not bundle a `luac`...

**Comment by foobert** [comment]
> Where did you get the byte code from? lua bytecode is not portable between platforms: you need to
> compile it on the target.

I did not know that. What I'm really trying to do is run [Whereigo](http://www.wherigo.com/) cartridges which are AFAIK multiple chunks of lua bytecode wrapped up in a file. There is also another project called [openwig](https://code.google.com/p/openwig/) which does the same using Java.

For now I've just been trying to run "hello world" by compiling the bytecode on my host and then running it inside the browser. But as I said I get a syntax error back.

> > FYI the file is compiled using the bundled luac

> We do not bundle a luac...

I mentioned that because I first tried bytecode compiled using luac 5.1.5 which did not work in my C PoC. Then I used luac version 5.2.3 from [the source tree](https://github.com/kripken/lua.vm.js/tree/master/lua). Which worked in C. So I should have written "bundled lua version" not "bundled luac".

I'll dig a bit deeper into openwig to see what they are doing to run the bytecode.

If you have any further insights on whether or not it's possible to run bytecode, I'd be interested to know.

**Comment by daurnimator** [comment]
> For now I've just been trying to run "hello world" by compiling the bytecode on my host and then running it inside the browser. But as I said I get a syntax error back.

> I mentioned that because I first tried bytecode compiled using luac 5.1.5 which did not work in my C PoC. Then I used luac version 5.2.3 from the source tree. Which worked in C. So I should have written "bundled lua version" not "bundled luac".

You need to compile luac with emscripten and run it in your browser (or node.js), rather than using your native C compiler.
This should let you get at least a "hello world" running :)

> If you have any further insights on whether or not it's possible to run bytecode, I'd be interested to know.

It is possible to run bytecode generated by a lua compiler of the same version (so no mixing lua 5.1 and 5.2) with the same C type sizes (`sizeof(int)` and `sizeof(size_t)`) and endianness.

I vaguely recall a converter floating around the lua mailing list, but a quick search didn't bring it up.

**Comment by foobert** [comment]
It seems that the Lua bytecode that I was originally trying to load is generated by a very old program using proprietary code, so I have no idea what kind of version I'm trying to load or if it even is valid Lua.

Thanks for the input, I'll be back if I can get it to run in C :-)
